export const reviews = [
  {
    id: 1,
    message:
      'Look no further if you are looking for a highly-skilled developer. As a developer myself, Erwin delivered. He is highly-skilled, competent, responsive and truly genuine person &amp; developer. He has worked for a couple of months on my project and delivered outstanding work, clean code and followed best practices during the entire development cycle. His communication is top-notch and he is highly proficient in English. He will also give any input if needed or recommend improvements where needed. Seriously, if you are looking for a full-stack web and/or hybrid mobile developer, stop skimming through the reviews and hire him now, or not because I will need him again soon.',
    firstname: 'Tomas',
    lastname: 'Verhelst',
    company: 'KotApp',
    published: true,
    title: 'Exceptional Full-Stack Developer',
  },
  {
    id: 2,
    message:
      "Erwin is a wonderful contractor to work with. He's highly communicative and is quick to offer his input and feedback. His English is fluent, he's quite charming and a good person over-all. He remains transparent at all times and I have never not felt comfortable when working with Erwin. He is an absolute joy to work with and his work is as good as it gets. I've completed 250+ projects on Odesk/Upwork and Erwin is in my top 2 all time best freelancers. I should stop with the praises so I can keep him all to myself! lol If you hire him, I can assure you he will be an asset!",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: true,
    title: 'Top-Tier Contractor',
  },
  {
    id: 3,
    message:
      'Erwin is one of the best contractors I have used on upwork in seven years. Extremely loyal, diligent, smart and with a real sense of business acumen which is rare on this site. He will reward any potential employee with his dedication, politeness and general good approach to the job in hand. He is not afraid to ask questions, or suggest better approaches. I very much enjoyed working with him on this job and look forward to working with him again in the future.',
    firstname: 'Cyril',
    lastname: 'Byrne',
    company: 'Varoom',
    published: true,
    title: 'Diligent and Business-Savvy Developer',
  },
  {
    id: 4,
    message:
      "Erwin is among the very best that I've been able to work with! He is transparent, highly skilled and is quick to offer his input when necessary. He's able to roll with the punches and delivers exactly what the client wants, 100% of the time. With over 300 successfully completed projects on upwork in the last 10 years, Erwin is in my top 3, BEST contractors of all time. You cannot go wrong hiring Erwin. Thanks for all you've done for me and my business!",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Top 3 Best Contractor',
  },
  {
    id: 5,
    message:
      'I reached out to Erwin with just a simple question of "do you have available time to work on a small project." He started asking me questions and before I realize it, he was already developing. I was not prepared to get started so quickly as I thought there would be time for planning. All I had was an idea and Erwin took that idea and gave it life. Thank you for such fast and awesome work!',
    firstname: 'Brian',
    lastname: 'Boyd',
    company: null,
    published: true,
    title: 'Efficient and Proactive Problem-Solver',
  },
  {
    id: 6,
    message:
      "Erwin is one of the best contractors I've had the pleasure of working with. He's completely transparent, polite, communicates REALLY well and above all else, he churns out quality code. He is quick to offer suggestions and listens to direction with the best of em. I would not hesitate to work With Erwin in the future. I am hiring him again, right now.",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Exceptional and Transparent Contractor',
  },
  {
    id: 7,
    message:
      'He is one of the best I have ever worked with and I have been completely satisfied with his work. He is quick to respond to questions, has a terrific work ethic, wants to do a quality job and has a great communication style. I highly recommend him for any project you have.',
    firstname: 'Joan',
    lastname: 'Azeka',
    company: 'PickleballWeather',
    published: true,
    title: 'Highly Satisfactory Performance',
  },
  {
    id: 8,
    message:
      "Erwin is among the very best that I have worked with here on Upwork. He thinks of things that I didn't and delivers very high quality work. I would not hesitate to work with him again and hope the opportunity presents itself sooner than later. Thanks again Erwin!",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Thoughtful and High-Quality Developer',
  },
  {
    id: 9,
    message:
      'Erwin is a fantastic resource for your advanced CSS needs. He promptly and efficiently completed my job, and I am ecstatic with the results! I highly recommend his services for anyone who is on the fence about hiring a freelancer to do some web work.',
    firstname: 'Ryan',
    lastname: 'Talbert',
    company: '9to5 Ninja',
    published: true,
    title: 'Advanced CSS Expert',
  },
  {
    id: 10,
    message:
      "Erwin is easy to work with. He remains transparent, follows direction well and offers suggestions to help make your project better. He thinks of things I do not and communicates better than most contractors I've worked with. I highly recommend Erwin!",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Collaborative and Insightful Developer',
  },
  {
    id: 11,
    message:
      'Sir Erwin is an excellent and very skilled developer that delivers everything he promises and beyond. Communication is truly outstanding and anyone working with him can rest assured that things will get completed before their deadline. Thank you!',
    firstname: 'Jackye',
    lastname: 'Govaerts',
    company: 'HelpDesk Heroes',
    published: true,
    title: 'Outstanding Developer with Excellent Communication',
  },
  {
    id: 12,
    message:
      "Erwin did a a fabulous job and exceeded my expectations. The end product was much better than I envisioned with virtually no bugs. I'm already planning a next set of changes with him. If you hire Erwin, I'm sure you will be very satisfied!",
    firstname: 'Neil',
    lastname: 'Sorathia',
    company: 'Booking Tool',
    published: true,
    title: 'Exceeding Expectations',
  },
  {
    id: 13,
    message:
      'What I thought would take several hours it not an entire day, my consolation with Erwin lasted just one hour but this hour saved me countless hours of work. This was money well spent! Thank you Erwin for your time and expertise.',
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Efficient and Expert Consultant',
  },
  {
    id: 14,
    message:
      "I was very impressed by Erwin's skills as a developer for our Vue 3 web app - and I would definitely work with him again. He has a very professional attitude and has delivered above and beyond expectations = 5 stars all round.",
    firstname: 'Olivia',
    lastname: 'Stodieck',
    company: 'Dapta',
    published: true,
    title: 'Professional Vue 3 Developer',
  },
  {
    id: 15,
    message:
      'Simply a great software developer. Unlike many programmers, he is willing and inquisitive to solve the requested task. With all his good intentions, he helped all our small and big problems, no matter what time it was.',
    firstname: 'Serhan',
    lastname: 'Kayalar',
    company: 'Socialays',
    published: true,
    title: 'Inquisitive and Solution-Oriented Programmer',
  },
  {
    id: 16,
    message:
      "Erwin is a pleasure to work with. He's smart, talented, and dedicated. He manages his time well, meets deadlines, and is committed to growing his skill set. I hope to work with him for many more projects in the future.",
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: true,
    title: 'Smart and Talented Collaborator',
  },
  {
    id: 17,
    message:
      'Added a very useful feature to my website that was rather complex but Erwin handled everything with ease from start to finish. He has excellent character and you cannot go wrong working with him.',
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Skilled and Characterful Web Developer',
  },
  {
    id: 18,
    message:
      "Erwin is a great Node / Nuxt.js developer who was able to implement everything I needed in a really good way. I'll definitely hire him again, as soon as my project moves on. Highly recommended.",
    firstname: 'Felix',
    lastname: 'Steuer',
    company: null,
    published: true,
    title: 'Expert in Node / Nuxt.js',
  },
  {
    id: 19,
    message:
      'Very good work ethic, I know that you will find that Erwin a very good freelancer to work with. Thanks again Erwin I will surly work with him again when I need to. Very good work thanks',
    firstname: 'Als',
    lastname: 'Eds',
    company: null,
    published: true,
    title: 'Very Good Work Ethic',
  },
  {
    id: 20,
    message:
      'He is exceptionally good! Great communication, highly skilled, he clearly understand the purpose of each technology he uses. I strongly recommend Erwin! I will definitely rehire him!',
    firstname: 'Corine',
    lastname: 'Morin',
    company: 'CyberPublicity',
    published: true,
    title: 'Exceptionally Skilled Communicator',
  },
  {
    id: 21,
    message:
      'Erwin is a Javascript wizard and he completed my project much quicker than I expected, saving me money and allowing me to mark another task complete. Thank you Erwin!!!',
    firstname: 'Brian',
    lastname: 'Boyd',
    company: null,
    published: false,
    title: 'Javascript Wizard',
  },
  {
    id: 22,
    message:
      'Another great contract with Erwin, he continues to impress with his dedication and abilities. Recommended to other clients and definitely will work with again. A+++',
    firstname: 'Cyril',
    lastname: 'Byrne',
    company: 'Varoom',
    published: true,
    title: 'Dedicated and Impressive',
  },
  {
    id: 23,
    message:
      "Erwin is really easy to work with. He's got a great set of skills and he completes the job on time, on budget and with the highest quality. Thank you Erwin!",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Skilled and Reliable Developer',
  },
  {
    id: 24,
    message:
      'Erwin is a very good developer, he know Nuxt and Vue perfectly and was able to complete the project on budget and time. 10/10 I would recommend Erwin.',
    firstname: 'Fabio ',
    lastname: 'Souto',
    company: 'Wheel Carnival',
    published: true,
    title: 'Nuxt and Vue Specialist',
  },
  {
    id: 25,
    message:
      'Erwin is always aiming for excellence, amazing communication, we love to work with him! He is very knowledgeable about frontend technologies',
    firstname: 'Corine',
    lastname: 'Morin',
    company: 'CyberPublicity',
    published: true,
    title: 'Frontend Technology Expert',
  },
  {
    id: 26,
    message:
      "Erwin does excellent work, communicates better than most I've worked with and is transparent! I highly recommend working with this man.",
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Excellent and Transparent Communicator',
  },
  {
    id: 27,
    message:
      'Excellent Freelancer! Amazing skills, he knows his technologies very well, excellent communication! I strongly recommend him!"',
    firstname: 'Corine',
    lastname: 'Morin',
    company: 'CyberPublicity',
    published: false,
    title: 'Amazingly Skilled Freelancer',
  },
  {
    id: 28,
    message:
      'Got all my questions answered in a great detail and with a high degree of professionalism. Thank you very much!',
    firstname: 'Kristina',
    lastname: 'Charisovaite',
    company: null,
    published: true,
    title: 'Professional and Detailed',
  },
  {
    id: 29,
    message:
      'Erwin was such a pleasure to work with and he has a lot of talent. Hope to work with him again soon!',
    firstname: 'Brian',
    lastname: 'Boyd',
    company: null,
    published: true,
    title: 'Talented and Pleasurable to Work With',
  },
  {
    id: 30,
    message:
      'Erwin designed a really nice web app for us from scratch using Figma. Great to work with him.',
    firstname: 'Olivia',
    lastname: 'Stodieck',
    company: 'Dapta',
    published: true,
    title: 'Creative Web App Designer',
  },
  {
    id: 31,
    message:
      'Erwin took what seemed like an impossible task and pulled it off wonderfully. Amazing skills!',
    firstname: 'Brian',
    lastname: 'Boyd',
    company: null,
    published: false,
    title: 'Master of Challenging Tasks',
  },
  {
    id: 32,
    message:
      'Erwin does excellent work and is 1 of my favorite contractors to work with! Thank you Erwin!!',
    firstname: 'Brian',
    lastname: 'Lack',
    company: 'Sin City Web Designs',
    published: false,
    title: 'Favorite and Excellent Contractor',
  },
  {
    id: 33,
    message:
      'He was prompt in replying and got done the work pretty soon. I would highly recommend him.',
    firstname: 'Sumit',
    lastname: 'Talreja',
    company: null,
    published: true,
    title: 'Prompt and Efficient',
  },
  {
    id: 34,
    message:
      'Erwin is a talented developer and did a fantastic job on this project. Highly recommended!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Talented Developer with Fantastic Results',
  },
  {
    id: 35,
    message:
      'Erwin is a great developer, very skilled and responsive, and always has great ideas.',
    firstname: 'Vishva',
    lastname: 'Dave',
    company: 'Instadapp Labs',
    published: true,
    title: 'Skilled and Responsive Developer',
  },
  {
    id: 36,
    message:
      'Erwin is a legend. He is an incredibly talented developer and an even better person!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Legendary Developer',
  },
  {
    id: 37,
    message:
      'He did a great job in building the scripts to properly package up my Vue.js app.',
    firstname: 'Stephane',
    lastname: 'Kasriel',
    company: null,
    published: true,
    title: 'Expert in Vue.js Script Building',
  },
  {
    id: 38,
    message:
      'Completed my requirements as required. Will like to work with him again.',
    firstname: 'Sumit',
    lastname: 'Talreja',
    company: null,
    published: false,
    title: 'Reliable and Requirement-Focused Developer',
  },
  {
    id: 39,
    message:
      'Erwin is a life-saver! Very talented developer and easy to work with!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Life-Saving Talented Developer',
  },
  {
    id: 40,
    message: 'Erwin is a stellar developer and person. I Highly recommend him!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Stellar Developer and Person',
  },
  {
    id: 41,
    message: 'Erwin is a fantastic developer and person..highly recommended!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Fantastic Developer and Person',
  },
  {
    id: 42,
    message: 'Erwin is a pleasure to work with and a fantastic developer!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Pleasurable and Fantastic Developer',
  },
  {
    id: 43,
    message: 'Excellent communicator, organizer and software engineer.',
    firstname: 'Mark',
    lastname: 'Marquez',
    company: 'THIO Inc.',
    published: true,
    title: 'Excellent Communicator and Organizer',
  },
  {
    id: 44,
    message: 'Talented. Responsive. Will hire again. Would recommend.',
    firstname: 'Scott',
    lastname: 'Smith',
    company: 'Dept5',
    published: true,
    title: 'Talented and Dependable',
  },
  {
    id: 45,
    message: 'Erwin is a super capable and competent developer!',
    firstname: 'Chris',
    lastname: 'Bellamy',
    company: null,
    published: false,
    title: 'Super Capable and Competent Developer',
  },
  {
    id: 46,
    message: 'Erwin is very skilled! Awesome to work with.',
    firstname: 'Jurre',
    lastname: 'Schieving',
    company: 'FinOps BV',
    published: true,
    title: 'Skilled and Enjoyable to Work With',
  },
  {
    id: 47,
    message: 'A pleasure to work with and very talented.',
    firstname: 'Brian',
    lastname: 'Boyd',
    company: null,
    published: false,
    title: 'Talented and Enjoyable Collaborator',
  },
  {
    id: 48,
    message: 'It was a pleasure to work with Erwin.',
    firstname: 'Melih',
    lastname: 'Tuzunoglu',
    company: 'Socialays',
    published: true,
    title: 'Pleasurable Collaboration',
  },
  {
    id: 49,
    message: 'Great operator. Would hire again.',
    firstname: 'Nick',
    lastname: 'Hudson',
    company: null,
    published: true,
    title: 'Reliable and Proficient Operator',
  },
  {
    id: 50,
    message: 'High skilled Vue developer.',
    firstname: 'Xue',
    lastname: 'Han',
    company: null,
    published: true,
    title: 'Highly Skilled in Vue Development',
  },
]
